### ISSUE TITLE
Sample is crashing.

### ISSUE THREAD

**Issue by EminYahyayev** [pizza/MaterialTabs#3]
Hi, I have just installed your sample from the play market. However, it's crashing after choosing the second configuration of tabs, i.e. 

launched app->configuration selected -> open tabs ->back->configured again->opening results in crash.

Xperia Z1 compact, Lolipop 5.0.1

Unfortunately, I haven't so much time now, maybe I'll look deeper inside your sample later :)

**Comment by pizza** [comment]
Hi @ewintory! Thanks for reporting this issue. I tried reproducing your steps and the app didn't crash on my phone. 

Surprisingly I didn't get any crash report from Crashlytics. Can you reopen the sample while connected to the internet (or maybe attach some logs if that's easier for you)? 

Thanks again! I'll look into it more in details in a few hours in all cases.

**Comment by pizza** [comment]
Update: I just received the crash report actually. Thanks, will look into it!

**Comment by EminYahyayev** [comment]
Sure, here you are :)

```
05-24 04:52:01.123    7970-7970/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: io.karim.materialtabs.sample, PID: 7970
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.RadioGroup.getCheckedRadioButtonId()' on a null object reference
            at io.karim.materialtabs.sample.MainActivity.goToTabsActivityButtonClicked(MainActivity.java:125)
            at io.karim.materialtabs.sample.MainActivity.onOptionsItemSelected(MainActivity.java:108)
            at android.app.Activity.onMenuItemSelected(Activity.java:2882)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:74)
            at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
            at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:4832)
            at android.view.View$PerformClick.run(View.java:19839)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

Btw I was connected to the internet while crash happened, so maybe you should check your Chrashlitics configuration as well...

**Comment by pizza** [comment]
@ewintory Check my previous comment ;-) but thanks anyway for the logs! I'll look into it very soon.

**Comment by EminYahyayev** [comment]
:+1:

**Comment by pizza** [comment]
@ewintory Hi again! I most probably fixed the issue. Can you please try to reproduce the steps you mentioned above with the updated APK here: https://github.com/pizza/MaterialTabs/blob/master/sample/sample-release.apk ? Thanks!

**Comment by EminYahyayev** [comment]
Hi, @pizza! Great, It works without any crashes :)

**Comment by pizza** [comment]
@ewintory Awesome. Thanks for your help :) Update submitted to Play Store.
